CREATE TABLE IF NOT EXISTS `#__membership_directory` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`size_of_company` VARCHAR(15)  NOT NULL ,
`year_joined` YEAR NOT NULL ,
`dues_2012` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`dues_2013` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`desingated_rep` VARCHAR(5)  NOT NULL ,
`new_2013` VARCHAR(3)  NOT NULL ,
`new_2012` VARCHAR(3)  NOT NULL ,
`term_expires` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`board_position` VARCHAR(20)  NOT NULL ,
`business_category` VARCHAR(30)  NOT NULL ,
`paid_2013` VARCHAR(3)  NOT NULL ,
`business_directory` VARCHAR(50)  NOT NULL ,
`company` VARCHAR(50)  NOT NULL ,
`address` VARCHAR(50)  NOT NULL ,
`city_state_zip` VARCHAR(50)  NOT NULL ,
`first_name` VARCHAR(20)  NOT NULL ,
`last_name` VARCHAR(20)  NOT NULL ,
`job_title` VARCHAR(50)  NOT NULL ,
`email` VARCHAR(50)  NOT NULL ,
`website` VARCHAR(30)  NOT NULL ,
`phone` VARCHAR(13)  NOT NULL ,
`cell` VARCHAR(13)  NOT NULL ,
`fax` VARCHAR(13)  NOT NULL ,
`contact` VARCHAR(30)  NOT NULL ,
`ap_email` VARCHAR(50)  NOT NULL ,
`description` TEXT NOT NULL ,
`referred_by` VARCHAR(50)  NOT NULL ,
`pass` VARCHAR(20)  NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_unicode_ci;

