<?include('header.php');?>

<p><strong>PRIVACY POLICY </strong><BR>
		 Charleston Lighting &amp; Manufacturing takes your privacy seriously. Our privacy policy is clear: We will collect no personally identifiable information about you when you visit our web site or use our services unless you choose to provide that information to us.</p>
		 <p><strong>What this Privacy Policy Covers </strong><BR>
		 This Privacy Policy covers Charleston Lighting &amp; Manufacturing treatment of personally identifiable information that we collect when you are on the CharlestonLighting.com site and when you use CharlestonLighting.com's services. This policy does not describe information collection policies on other sites, including those linked to or from CharlestonLighting.com</p>
		 <p><strong>What Type of Information We Collect</strong><BR>
		 CharlestonLighting.com does not collect any personally identifiable information about you other than information that you affirmatively choose to submit to us, such as your e-mail address and name when you subscribe to one or more of our e-mail-based newsletters. CharlestonLighting.com also automatically collects aggregate information about the use of our site, including which pages are most frequently visited, how many visitors we receive daily, and how long visitors stay on each page.</p>
		 <p><strong>Cookies</strong><BR>
		 Cookies are small pieces of information that are sent to a user's Internet browser when that user accesses a Web page. The Cookie is then saved to the user's hard disk so that on subsequent visits to the site the host computer will know what information the user accessed on previous visits and/or might want to access on future visits. Charleston Lighting &amp; Manufacturing may use Cookies, and use of Cookies is standard practice for many Web sites. In fact, your browser is most likely programmed to accept Cookies. However, if you wish to disable this function, you can do so by de-selecting this option in your browser. To the extent that information regarding you is available from your Internet browser, Charleston Lighting &amp; Manufacturing reserves the right to use such information to record traffic and user information statistics for the purposes of optimizing our Web site content and structure. Charleston Lighting &amp; Manufacturing will not share such information with a third party. To the extent that you provide us with information regarding yourself for purposes of receiving additional information or firm publications, Charleston Lighting &amp; Manufacturing will use such information only for that purpose.</p>
		 <p><strong>How We Use the Information We Collect</strong><BR>
		 The personally identifiable information we collect from and about you may be used to provide e-mail-based newsletters and other information to you as you request and to notify you from time to time about services offered by CharlestonLighting.com or other entities associated with CharlestonLighting.com. We may provide personally identifiable information we collect about you to third parties only when such third parties desire to provide, on a limited basis, information that may be of interest to you. We may disclose information about you if we have a good-faith belief that we are required to do so by law or legal process, to respond to claims, or to protect the rights, property or safety of Charleston Lighting &amp; Manufacturing or others.</p>
		 <p><strong>Third-Party Traffic Analysis</strong><BR>
		 CharlestonLighting.com uses a program to analyze traffic to this web site. The program does not create individual profiles for visitors. Unlike some tracking services it does not have a database of individual profiles for each visitor but only collects aggregate data.</p>
		 <p><strong>Opting-Out, Corrections and Cancellations</strong><BR>
		 Upon request, Charleston Lighting &amp; Manufacturing will (a) remove you and your personal information from our database; (b) correct personal information that you state is erroneous; or (c) permit you to "opt out" of further email contact (excepting notification of major changes to the service) while still allowing access to the site. To request a correction or cancellation, contact us.</p>
		 <p><strong>Changes to this Privacy Policy</strong><BR>
		 Charleston Lighting &amp; Manufacturing may revise and update this Privacy Policy at any time by posting such revised Privacy Policy at http://www.CharlestonLighting.com/security.php. Your continued usage of CharlestonLighting.com will mean you accept those changes.</p>
		 
<?include('footer.php');?>